'use client';

import { useEffect, useRef } from 'react';
import { useStore } from '@/lib/store';
import { IProject } from '@/models/Project';
import { toast } from 'sonner';

interface ProjectInitializerProps {
    project: IProject;
}

export default function ProjectInitializer({ project }: ProjectInitializerProps) {
    const {
        setNodes, setEdges, setClusters, setInsight, setTechStack, setMvpChecklist, setNextSteps, setTags, setProjectId, setIdeaId, setGraphData, setPrompt,
        nodes, edges, clusters, insight, techStack, mvpChecklist, nextSteps, tags, graphData, prompt
    } = useStore();
    const initialized = useRef(false);
    const saveTimeout = useRef<NodeJS.Timeout>(null);

    // Initialize store
    useEffect(() => {
        if (!initialized.current) {
            // Reset store to clear any previous project data
            useStore.getState().reset();

            setProjectId(project._id.toString());
            if (project.ideaId) {
                setIdeaId(project.ideaId);
            }

            if (project.data) {
                // Sanitize nodes to ensure all labels are strings
                // IMPORTANT: Filter out card nodes - they will be regenerated by ProjectCards component
                if (project.data.nodes) {
                    const sanitizedNodes = project.data.nodes
                        .filter((node: any) => node.type !== 'card')
                        .map((node: any) => ({
                            ...node,
                            data: {
                                ...node.data,
                                label: typeof node.data?.label === 'string'
                                    ? node.data.label
                                    : String(node.data?.label || 'Node')
                            }
                        }));
                    setNodes(sanitizedNodes);
                }
                if (project.data.edges) setEdges(project.data.edges);
                if (project.data.clusters) setClusters(project.data.clusters);
                if (project.data.insight) setInsight(project.data.insight);
                if (project.data.techStack) setTechStack(project.data.techStack);
                if (project.data.mvpChecklist) setMvpChecklist(project.data.mvpChecklist);
                if (project.data.nextSteps) setNextSteps(project.data.nextSteps);
                if (project.data.tags) setTags(project.data.tags);
                if (project.data.graphData) setGraphData(project.data.graphData);
                if (project.data.prompt) setPrompt(project.data.prompt);
            }
            initialized.current = true;
        }
    }, [project, setNodes, setEdges, setClusters, setInsight, setTechStack, setMvpChecklist, setNextSteps, setTags, setProjectId, setIdeaId, setGraphData, setPrompt]);

    // Auto-save
    useEffect(() => {
        if (!initialized.current) return;

        const saveData = async () => {
            try {
                const data = {
                    nodes,
                    edges,
                    clusters,
                    insight,
                    techStack,
                    mvpChecklist,
                    nextSteps,
                    tags,
                    graphData,
                    prompt
                };

                const res = await fetch(`/api/projects/${project._id}`, {
                    method: 'PUT',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ data }),
                });

                if (!res.ok) {
                    throw new Error('Failed to save');
                }
                console.log('Project saved successfully');
            } catch (error) {
                console.error('Error saving project:', error);
                toast.error('Failed to save project');
            }
        };

        // Debounce save
        if (saveTimeout.current) {
            clearTimeout(saveTimeout.current);
        }

        saveTimeout.current = setTimeout(saveData, 2000); // Save after 2 seconds of inactivity

        return () => {
            if (saveTimeout.current) {
                clearTimeout(saveTimeout.current);
            }
        };
    }, [nodes, edges, clusters, insight, techStack, mvpChecklist, nextSteps, tags, graphData, prompt, project._id]);

    return null;
}
